### ISSUE TITLE
Add features to docs.rs config to generate proper documentation

### ISSUE THREAD

**Issue by Sitin** [rustsim/salva#65]
Right now certain parts of documentation for optional features are not generated. For, example, the [integration](https://docs.rs/salva3d/latest/salva3d/integrations/index.html) is missing.

We can update `build/salva3d/Cargo.toml` and `build/salva2d/Cargo.toml`:

```toml
[package.metadata.docs.rs]
# Features to include into `docs.rs` documentation
features = [
    "rapier",
    # ...
]
```
